---

language: python
python: "2.7"
sudo: required
dist: trusty

env:
  global:
    - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/usr/local/sbin
    - GEM_HOME=
    - GEM_PATH=

# Install ansible
addons:
  apt:
    packages:
    - python-setuptools

services:
  - mysql

install:
  - sudo -H easy_install pip
  # http://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2
  - sudo -H pip install -U pyOpenSSL cryptography idna certifi
  - sudo -H pip install -U urllib3
  # https://github.com/ansible/ansible/issues/23642#issuecomment-297469043
  - sudo -H pip install -U ndg-httpsclient

  # Install ansible
  - sudo -H pip install -U ansible

  # Check ansible version
  - ansible --version

before_script:
  - mysql -e 'CREATE DATABASE gitlabhq_production;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('farm') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql

script:
  - ./test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
