---

- name: yarn
  command: yarn install --production --pure-lockfile
  args:
    chdir: /home/git/gitlab
  become: yes
  become_user: git

- name: compile assets
  command: bundle exec rake gitlab:assets:clean gitlab:assets:compile RAILS_ENV=production NODE_ENV=production
  args:
    chdir: /home/git/gitlab
  become: yes
  become_user: git

- name: compile gettext
  command: bundle exec rake gettext:compile RAILS_ENV=production
  args:
    chdir: /home/git/gitlab
  become: yes
  become_user: git

- name: clear cache
  command: bundle exec rake cache:clear RAILS_ENV=production
  args:
    chdir: /home/git/gitlab
  become: yes
  become_user: git
