---

- name: yarn
  command: yarn install --production --pure-lockfile
  args:
    chdir: /home/git/gitlab
  become: yes
  become_user: git

# https://gitlab.com/gitlab-org/gitlab-ce/issues/38457
- name: yarn bug 9.4 to 9.5
  command: yarn add ajv@^4.0.0
  args:
    chdir: /home/git/gitlab
  become: yes
  become_user: git

- name: compile assets
  command: bundle exec rake gitlab:assets:clean gitlab:assets:compile RAILS_ENV=production NODE_ENV=production
  args:
    chdir: /home/git/gitlab
  become: yes
  become_user: git
  async: 1800
  poll: 0
  register: async_gitlab_compile_assets

- name: poll compile assets
  async_status:
    jid: "{{ async_gitlab_compile_assets.ansible_job_id }}"
  become: yes
  become_user: git
  register: async_gitlab_compile_assets_result
  until: async_gitlab_compile_assets_result.finished
  retries: 30
  delay: 60

- name: compile gettext
  command: bundle exec rake gettext:compile RAILS_ENV=production
  args:
    chdir: /home/git/gitlab
  become: yes
  become_user: git

- name: clear cache
  command: bundle exec rake cache:clear RAILS_ENV=production
  args:
    chdir: /home/git/gitlab
  become: yes
  become_user: git
