---

- name: get gitlab_workhorse_version
  slurp:
    src: /home/git/gitlab/GITLAB_WORKHORSE_VERSION
  register: gitlab_workhorse_version
  become: yes
  become_user: git

- name: update gitlab-workhorse
  git:
    repo: 'https://gitlab.com/gitlab-org/gitlab-workhorse.git'
    dest: /home/git/gitlab-workhorse
    version: "v{{ gitlab_workhorse_version['content'] | b64decode }}"
    update: yes
    force: yes
  become: yes
  become_user: git
  notify: restart_gitlab

- name: compile gitlab-workhorse
  command: make
  args:
    chdir: /home/git/gitlab-workhorse
  become: yes
  become_user: git
