---

- name: init db
  command: bundle exec rake gitlab:setup RAILS_ENV=production GITLAB_ROOT_PASSWORD={{ gitlab_root_password }} GITLAB_ROOT_EMAIL={{ gitlab_root_email }} force=yes
  args:
    chdir: /home/git/gitlab
  become: yes
  become_user: git

- name: add_limits_mysql
  command: bundle exec rake add_limits_mysql RAILS_ENV=production
  args:
    chdir: /home/git/gitlab
  become: yes
  become_user: git
