---

- name: add vhost
  template:
    src: vhost.conf
    dest: /etc/nginx/vhosts/gitlab.conf
    mode: 0644
  become: yes

- service:
    name: nginx
    state: restarted
  become: yes

- wait_for:
    port: 80

- name: invoke certbot
  command: "{{ gitlab_certbot_cmd }}"
  become: yes

- stat:
    path: /etc/letsencrypt/live/{{ gitlab_fqdn }}/fullchain.pem
  register: gitlab_lecert
  become: yes
